version: '3.8'

services:
  server:
    image: 'nginx:stable-alpine'
    container_name: nginx_server
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    depends_on:
      - php
  npm:
    image: 'node:12'
    volumes:
      - .:/var/www/html
  php:
    build:
      context: docker-files
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - .:/var/www/html